### ISSUE TITLE
Lag when scrolling with fingers and when zooming 

### ISSUE THREAD

**Issue by Heiseneberg-maybe** [flxzt/rnote#262] opened 2022-09-25 14:33 UTC
I have a 2in1 and I use Rnote to take notes during lessons

**Describe the bug**
When moving trough a file using the fingers, either scrolling or moving sideways the application lags.
The same happens when zooming.
This behaviour happens after writing a certain number of strokes.
The more I zoom the worse the lag becomes.
This happens when using fingers to move the view, when using the touchpad this happens but it's barely noticeable and it becomes more noticeable only at around maximum zoom (circa 500%) but still negligible. 
When using the scrollbars or the zoom in the three dots menu the app behaves like it behaves when using the tocuhpad.
The cause of the problem seems to be related to the touch input.

**To Reproduce**
1. Open/Create a file with a lot of strokes 
2. Start moving the view with the fingers or zooming 
3. Wait for the action to finish(when zooming sometimes it doesn't zoom where expexted )
4. Notice the lag

**Expected behavior**
When moving the view and/or zooming the action takes place immediately

** Console Output **
Running with `flatpak run com.github.flxzt.rnote`  creates this: 
(rnote:2): Gtk-CRITICAL **: 16:13:38.217: The layout manager of type GtkBoxLayout 0x555abbf82870 does not create GtkLayoutChild instances

**Desktop (please complete the following information):**
 - OS: [Fedora] 
 - Version [36]
 - Installation source [Flatpak]  
 - Desktop Environment [e.g. Gnome 42.4]
 - At this link you can see the exact hardware I have: https://linux-hardware.org/?probe=be1d17baa4

**Additional context*
The video shows how the zoom and scrolling behaves when using fingers and how they behave when using scrollbars and the zoom in the three dot menu
[Rnote lag.webm](https://user-images.githubusercontent.com/104737846/192149032-91a0c024-64fa-4062-8223-3199765d1eeb.webm)

This behaviour is present when using Ubuntu 22.04 too.

**Comment by Heiseneberg-maybe** [comment] 2022-09-26 09:21
I'm sorry, I forgot to say that the performance is great when using the laptop in charge with its 65W charger and that after plugging the laptop in charge the performance problems disappear almost instantly.
Surprisingly the performance problems remain about the same when using a 45W charger.

**Comment by Heiseneberg-maybe** [comment] 2022-09-26 14:06
Yes, I use the default power manager of fedora, it should be gnome power-profiles-daemon.
Unfortunately there is no difference between power saver and balanced mode(I don't have a performance mode)

**Comment by p-fruck** [comment] 2022-10-23 14:06
I am facing the same issue even with performance mode enabled. Do you have another idea what could be causing this issue?

**Comment by D0V4HKIIN** [comment] 2022-11-09 15:48
i have the same issue ):

**Comment by D0V4HKIIN** [comment] 2023-01-06 10:33
I took a big file and opened it with my limited knowledge of flamegraph and scrolled and zoomed around with my fingers a bit. It looks like the calc_height() function is the one that is very slow. Makes sense because it loops over all strokes and gets it's bounding box which is slow when there are many strokes.

I don't know why it doesn't do that when scrolling with the mouse. Needs more looking into.

A performance gain could be to dynamically track the height at each new stroke and keep it in memory instead of recalculating it each time.

![graph](https://user-images.githubusercontent.com/43830391/210986330-2725ed91-ec31-44a2-bfe0-6ebe14c8d4b3.svg)

As a reference, the file I tested on is 5 megabytes big and has 12 pages of handwritten text.

**Comment by flxzt** [comment] 2023-01-06 10:43
Ah, thats insightful, thanks! So only to confirm: this only happens in "continuous-vertical" mode?

**Comment by D0V4HKIIN** [comment] 2023-01-06 10:47
yes! I just tested fixed and infinite and they work just fine scrolling and zooming.

**Comment by flxzt** [comment] 2023-01-06 10:51
I see. That calculation shouldn't even be necessary, because the height is not dependent on the camera offset

**Comment by flxzt** [comment] 2023-01-06 10:52
should be fixed. Thanks, the flamegraph was really helpful. I should starting using it more myself

**Closed** 2023-01-06 10:52 UTC
Labels: performance, high prio

**Comment by flxzt** [comment] 2023-01-06 10:57
Regarding mouse scrolling: You only scroll on the canvaswrapper, the canvas never expands when doing that. in contrast, dragging with middle mouse button / touch dragging expands the canvas in infinite mode. Thats the reason it was behaving differently.

**Comment by D0V4HKIIN** [comment] 2023-01-06 11:10
I can confirm that it doesn't lag anymore when dragging or zooming on the latest commit.

Shouldn't dragging and scrolling have the same behavior?

**Comment by flxzt** [comment] 2023-01-06 11:35
Maybe, but it felt intuitive to me that there is a stopping point with a regular scroll, and a drag is a different operation. And it would complicate the implementation, the scrolls come with the scrolledwindow, we'd need to implement them manually then. So as long as nobody complains, I think it is fine

**Comment by D0V4HKIIN** [comment] 2023-01-06 12:59
Makes sense to me

**Comment by Heiseneberg-maybe** [comment] 2023-01-07 14:55
I can confirm that the issue has been solved for me too on the latest commit and when using the other modes.
It's too bad that I didn't notice that this only happens in "continuous-vertical" mode, unfortunately I never used the other modes.
Nonetheless thank you very much flxt and D0V4HKIIN for the fix and the work on the app
