### ISSUE TITLE
Edit selected contents.

### ISSUE THREAD

**Issue by amit9838** [flxzt/rnote#418] opened 2022-12-23 11:12 UTC
Unable to edit any object drawn in the past, like curve color, font size/style?

Suggestion:
I think, it can be done  by introducing new selection tool **`Edit tool`**  which have ability to select only one object at a time and edit it accordingly.  May be use it as a global tool to avoid loosing selctions.

**Comment by flxzt** [comment] 2022-12-24 14:33
kind of a duplicate of #55, lets track adding an edit option for brush strokes and shapes there.

**Closed** 2022-12-24 14:34 UTC
Labels: duplicate
