### ISSUE TITLE
Moving Capability for Toolbars

### ISSUE THREAD

**Issue by Tahinli** [flxzt/rnote#1079] opened 2024-04-12 13:33 UTC
If moving ability could be implemented for these bars, it would be nice. People should be able to rearrange them in certain condition.

![image](https://github.com/flxzt/rnote/assets/96421894/92ec0368-733b-400c-85d6-e158fa3a3b67)
![image](https://github.com/flxzt/rnote/assets/96421894/a47540ac-b526-45d5-86cb-33cf52a73cb1)
![image](https://github.com/flxzt/rnote/assets/96421894/8983530f-9e46-4de7-b147-ab96dbd5cf67)

**Comment by flxzt** [comment] 2024-04-13 08:22
duplicate of #655

**Closed** 2024-04-13 08:22 UTC
Labels: duplicate
