### ISSUE TITLE
Keybindings for changing  Pen color 

### ISSUE THREAD

**Issue by mohammedbilalns** [flxzt/rnote#1049] opened 2024-03-16 16:45 UTC
It would be great to have a keybinding for switching between two user-selected pen colors.

**Comment by mahdihasan2006** [comment] 2024-03-19 13:32
Indeed customizable key-binding for each color would be better.

**Comment by flxzt** [comment] 2024-03-27 18:57
duplicate of #656

**Closed by flxzt** 2024-03-27 18:57 UTC
