### ISSUE TITLE
An icon isn't loading correctly from themes

### ISSUE THREAD

**Issue by MooWaza** [flxzt/rnote#1074] opened 2024-04-11 03:51 UTC
When using non-adwaita icon themes, one icon won't ever load properly. The hamburger menu will appear grey and with the wrong icon unless the default adwaita version of the icon is present in the theme. (Left in the image)

![image](https://github.com/flxzt/rnote/assets/64917557/4392d8de-f9a1-4e54-8fbc-df887c626dba)

The issue's been seen while using themes such as papirus and whitesur, not with adwaita or morewaita

 - OS: Fedora 39
 - App Version: 0.10.2
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 45.2
 - Display Server: Wayland
 - Input Source: Mouse and Keyboard / On-Screen-Tablet

**Comment by flxzt** [comment] 2024-04-12 07:49
duplicate of #995

**Closed by flxzt** 2024-04-12 07:49 UTC
