### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by BomberBotz** [flxzt/rnote#836] opened 2023-10-11 23:19 UTC
Android version of this app that would work for android tablets and Samsung ultra phones (or any android device with stylus support). For my use case, since I use MEGA as my means to sync my files, it would be great for Rnote to continue to have offline dedicated folder storage (that you can pick) in order to make syncing with various different providers easier.

**Comment by flxzt** [comment] 2023-10-12 04:00
duplicate of #390

**Closed by flxzt** 2023-10-12 04:00 UTC
Labels: duplicate
