### ISSUE TITLE
croping image

### ISSUE THREAD

**Issue by kesu33** [flxzt/rnote#1183] opened 2024-08-22 17:44 UTC
**Please submit only one feature request in one issue!**  
croping option image after selection the image.

**Is your feature request related to a problem? Please describe.**  
After selecting an image from folder , I want to do crop the image.

**Describe the solution you'd like**  
If there is a croping tool in toolbar.

**Comment by flxzt** [comment] 2024-08-23 18:21
duplicate of #794.

**Closed by flxzt** 2024-08-23 18:21 UTC
