### ISSUE TITLE
Navigating Rnote with a stylus

### ISSUE THREAD

**Issue by RushingAlien** [flxzt/rnote#193] opened 2022-05-29 07:40 UTC
**Is your feature request related to a problem? Please describe.**
Pen navigation with rnote with only a stylus isn't so great right now, usually some apps can have pen button mapped to middle mouse button so i can hold that button to drag the canvas around, and also ctrl plus the pen button to zoom in zoom out via moving the cursor up and down while both ctrl and pen button are still held down this is what i do with Krita, GIMP, Xournal++, Inkscape, etc.

**Describe the solution you'd like**
For pen buttons to be mappable to a keyboard or mouse action, not just tools.

**Comment by flxzt** [comment] 2022-05-29 18:32
duplicate of #189 with the ctrl + drag suggestion.
Mapping the pen buttons to a keyboard / mouse key wont be implemented / is not how the input system works, but the feature for better mapping to individual tools is tracked in #18

**Closed by flxzt** 2022-05-29 18:32 UTC

**Comment by RushingAlien** [comment] 2022-05-30 01:03
I see, so I have heard from the OpenTableDriver team as well. But is it possible to map the pen buttons to the same action that middle click does for example, not mapped to the middle click button perse, but just the same action that middle click does?

**Comment by flxzt** [comment] 2022-05-30 01:37
definitely. I suppose the middle mouse button could also be made reconfigurable, and the shortcut actions could be extended to include navigation controls
