### ISSUE TITLE
Extra options for long display input

### ISSUE THREAD

**Issue by karasumikuwu** [flxzt/rnote#979] opened 2024-01-15 23:04 UTC
Hi!
I love rnote and I use it daily for university note taking. 

Would it be possible to add extra options like copy, cut, paste if you press and hold. Like in Goodnotes where if you stayed on the display for like 1s or so without moving, some editing options would pop up. 
It would make editing documents so much easier. 

I really hope this makes any sense. 
I'm not a programmer at all so I don't know the right vocabulary for it, sorry xD

**Comment by flxzt** [comment] 2024-01-17 09:30
I'll close as duplicate of #704

**Closed by flxzt** 2024-01-17 09:30 UTC
Labels: enhancement
