### ISSUE TITLE
Drawing via Touch Input gets locked on current Flatpak release.

### ISSUE THREAD

**Issue by pertrush1** [flxzt/rnote#115] opened 2022-02-16 15:23 UTC
**Describe the bug**
When drawing with touch input, regularly, CPU goes to 100% (while normally being at 4-10%), not drawing anything but rendering of the page still functions.

**To Reproduce**
Sadly, I cannot 100% reproduce it. It might have to do with zooming than quickly starting drawing but not sure.

**Expected behavior**
Normal, continuous and uninterrupted drawing and zooming.

** Console Output **
Nothing besides normal console log.

**Screenshots**
Imagine 100% CPU usage in htop while not being able to draw.

**Desktop (please complete the following information):**
 - OS: Elementary OS
 - Version 6.1
 - Installation source Flatpak
 - i3Gaps

**Comment by pertrush1** [comment] 2022-02-18 12:14
Actually I think this error is related to the issue. Got it when force closed the application,while it got locked, due to anger.

ERROR rnote::strokesstate::render_comp > tasks_tx.send() UpdateStrokeWithImages failed in regenerate_rendering_for_stroke_threaded() for stroke with key StrokeKey(2v1), with Err, sending on a closed channel

**Comment by pertrush1** [comment] 2022-02-19 15:18
Regarding the question:
1. The UI still works, only strokes are not rendering. But they are still buffered and once the locking stops/restart the application (saving also sometimes work), they appear. The application responds to everything (zoom, pan, setting changes, etc) perfectly (albeit a bit slower due to the CPU usage)
2. From my testing, it only happens with touch inputs
3. It usualy happens if I zoom than start drawing too fast (it feels like if I dont let the screen to fully render and I start drawing it locks). This happens with small 10 pages pdfs, as well as longer, 60 pages one. The locking starts from first stroke, but more strokes I try to draw, the more time it will get locked. Usualy, from 1 stroke, it locks for about 30 seconds but multiple strokes take about 1.5-2 mins to start rendering the strokes.
4. Sadly I cannot screen capture as I downgraded rnote to previous release where this doesnt happen and this weekend Im buzy. Sorry.

**Comment by flxzt** [comment] 2022-05-09 11:55
I remember seeing this in the code while refactoring parts of it. This was a issue that caused excessive rerendering while zooming that resulted in a app freeze. Could you try the latest version and report if this is fixed?

**Comment by flxzt** [comment] 2022-09-25 11:58
I cannot reproduce this in the latest version, I assume it is fixed with the refactor.

**Closed by flxzt** 2022-09-25 11:58 UTC
Labels: bug
