### ISSUE TITLE
split shapes with eraser

### ISSUE THREAD

**Issue by capi1O** [flxzt/rnote#1162] opened 2024-07-29 17:15 UTC
When using the eraser in "Split Strokes" mode on lines made with Shaper tool it erases the whole line.

Expected behaviour => should erase only the part under the cursor and effectively splitting the line in two vectors.
This is the expected behaviour for me since it's what I've seen in many apps (Concepts, Illustrator, Inkscape)

If not doing this by default rnote should have an additional mode in Eraser such as "Split Strokes and Shapes"

**Comment by Doublonmousse** [comment] 2024-07-29 18:50
Duplicate of #596

**Closed** 2024-07-29 18:50 UTC
Labels: duplicate

**Comment by capi1O** [comment] 2024-07-29 20:50
Sorry for missing the duplicate...
