### ISSUE TITLE
Movement shortcuts for typewriter mode

### ISSUE THREAD

**Issue by LeSnake04** [flxzt/rnote#609] opened 2023-04-06 17:04 UTC
**Is your feature request related to a problem? Please describe.**

Currently e.g.  ctrl  + left moves the curser one character to the left. Most other typical movement/selection shortcuts do nothing

**Describe the solution you'd like**
Implement the following shortcuts in typewriter mode:
ctrl + left/right  = move curser to next/previos word
ctrl + shift + left/right = select until next/previos word
pos1/end = move cursor to start/end of line
shift + pos1/end = select until start/end of line
ctrl + page up/down = move cursort to start/end of text
ctrl + page up/down = select text start/end of text

**Describe alternatives you've considered**
Buttion to show a popup whith a native gtk text field to edit the contents, which should support this movement out of the box

**Additional Context**
This is one of the main reasons I current have to go back to xournal sometimes

**Comment by flxzt** [comment] 2023-04-06 17:11
duplicate of #560

**Closed by flxzt** 2023-04-06 17:11 UTC
