### ISSUE TITLE
save-file dialog crashes

### ISSUE THREAD

**Issue by LuNeder** [flxzt/rnote#648] opened 2023-04-25 22:32 UTC
**Describe the bug**  
Saving does not work. When you click "save" or "save as" and name the document, no file is created.
The only way to save the file is closing the app and using the dialog that asks if you want to save before closing (apparently updating files that were created this way works as expected)

Opening other folders in the file selector save thing also makes the selector abend

There is one exception to this bug: if you open an empty folder and save the file in it. Then it works (sometimes? it did not work when I recorded lol).

**To Reproduce**  
1. Go to hamburger menu
2. Click on Save or Save As
3. Name the file whatever
4. No files are created/saved

**Expected behavior**  
When clicking Save or Save As, a file should be created on the selected folder, saving the file.

**Console Output**  
No output is given

**Screenshots**  

https://user-images.githubusercontent.com/19750714/234418340-2bc40e24-e5e3-46c3-ab3e-ad70951f060b.mov

**Desktop (please complete the following information):**  
 - OS: OpenSUSE Tumbleweed
 - App Version: rnote v0.6.0
 - Installation Source: Flatpak
 - Desktop Environment: XFCE

**Comment by flxzt** [comment] 2023-04-28 12:39
In the last few seconds in your sceencast it looks like the filechooser is crashing. Did you try saving through this dialog in other gtk4 / adwaita apps?
Or maybe try out another file manager (for example, nautilus).

Because rnote should log successful or unsuccessful saves, it looks like the filechooser simply does not give picked file path back (equivalent) to cancelling).

**Comment by LuNeder** [comment] 2023-05-01 15:57
I tried gnome text editor and liferea, both seem to save files succssesfully. Pretty sure that the filepicker that rnote and both of those apps are opening is nautilus (even tho my default is thunar).

Here's the journalctl log of when the filepicker crash happens: [rnote-filepicker-abend.txt](https://github.com/flxzt/rnote/files/11366378/rnote-filepicker-abend.txt)

Apparently it might have something to do with the filter, according to someone else that tried it. They said that in KDE it's appearing without a filter too (even tho they were not able to reproduce the crash). For me, no filter selection option is shown at all.

**Comment by flxzt** [comment] 2023-05-06 21:34
This definitely reads like it is a bug in either xdg-desktop-portal-gtk, gtk or the gtk-rs (the rust bindings). I can't reproduce it unfortunately (neither via flatpak or with a native installation). A brief search through issue-trackers reveals [this reported issue](https://github.com/flatpak/xdg-desktop-portal-gtk/issues/325), though the logs don't match exactly what you are experiencing.

What might already be a possible "fix": #660 switched to the new FileDialog API instead of previously FileChooserNative. Could you test if it fixed it?

**Comment by 132ikl** [comment] 2023-10-01 17:05
I have this same issue, using 0.8.2 native and flatpak. I can usually get the file to save by just trying over and over again until it eventually works. I have the same issue with the file picker for Export Document, but sometimes the dialog doesn't open at all. The `Import File` dialog never opens. I consistently get this error in the log for xdg-desktop-portal when the file picker doesn't work or doesn't open at all:

```
Backend call failed: Message recipient disconnected from message bus without replying
```

and this error in the rnote log:

```
2023-10-01T17:03:05.921Z DEBUG rnote::dialogs::export > no file selected in save doc as dialog (Error or dialog dismissed by user), Error { domain: gtk-dialog-error-quark, code: 2, message: "Dismissed by user" }
```

I have definitely also seen the filter error @LuNeder posted, although I can't seem to produce it myself at the moment.

**Comment by 132ikl** [comment] 2023-10-02 20:57
Update: If I `systemctl mask` the `xdg-desktop-portal` service, everything becomes fully functional.

**Comment by LuNeder** [comment] 2023-10-02 20:59
Of course it’s xdg’s fault, it’s always xdg’s fault
Em 2 de out. de 2023, 17:57 -0300, 132ikl ***@***.***> escreveu:

**Comment by 132ikl** [comment] 2023-10-03 22:04
It seems like `xdg-desktop-portal-lxqt` works. I was using `xdg-desktop-portal-gtk` before.

**Comment by flxzt** [comment] 2023-11-12 09:20
alright, I don't think this was/is an issue on Rnote's side but one that needs to be/is already fixed in gtk-portal.

**Closed by flxzt** 2023-11-12 09:20 UTC
Labels: bug, cant-reproduce
