### ISSUE TITLE
Implement Ctrl+Y to redo.

### ISSUE THREAD

**Issue by MubinMuhammad** [flxzt/rnote#1265] opened 2024-10-25 15:06 UTC
Today, most programs support Ctrl+Y to redo the thing you did. It makes it easier to redo instead of pressing the arrows. Because most of the time the cursor is on the board and a keyboard shortcut would help.

Thanks.

**Comment by MubinMuhammad** [comment] 2024-10-27 07:24
Thanks, but normal apps are different than Rnote. So preferably, Ctrl+Y should also be an option.

**Comment by Anshsahu0802** [comment] 2024-10-28 14:55
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by RayJW** [comment] 2024-10-29 10:43
> Thanks, but normal apps are different than Rnote. So preferably, Ctrl+Y should also be an option.

I think normal apps is the wrong word here. There are a lot of apps that use `Ctrl + Shift + Z` for redo, especially in the creative space. Either way, this should probably be closed as a duplicate of #590.

**Comment by flxzt** [comment] 2024-10-29 11:46
yes, I agree.

**Closed by flxzt** 2024-10-29 11:46 UTC
