### ISSUE TITLE
Rnote crashing on startup on Fedora Kinoite 38 with KDE 5.27

### ISSUE THREAD

**Issue by thatLeaflet** [flxzt/rnote#515] opened 2023-02-17 05:57 UTC
**Describe the bug**
Rnote is crashing on launch

**To Reproduce**
1. Install Kinoite 38 Prelease
2. Install Rnote as flatpak
3. Attempt to run Rnote

**Expected behavior**
The app would launch

** Console Output **

> [evan@k-jinx]~% flatpak run com.github.flxzt.rnote
> 
> (rnote:2): Gtk-WARNING **: 00:48:56.829: Unknown key gtk-modules in /home/evan/.var/app/com.github.flxzt.rnote/config/gtk-4.0/settings.ini
> 
> (rnote:2): Adwaita-WARNING **: 00:48:56.867: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', rnote-ui/src/strokewidthpicker/strokewidthpreview.rs:97:35
> stack backtrace:
>    0:     0x56110fe539c0 - <unknown>
>    1:     0x56110f9717ce - <unknown>
>    2:     0x56110fe30ba4 - <unknown>
>    3:     0x56110fe551af - <unknown>
>    4:     0x56110fe54daf - <unknown>
>    5:     0x56110fe55e2d - <unknown>
>    6:     0x56110fe558c4 - <unknown>
>    7:     0x56110fe5585c - <unknown>
>    8:     0x56110fe55831 - <unknown>
>    9:     0x56110f73e972 - <unknown>
>   10:     0x56110f73ea6c - <unknown>
>   11:     0x56110f84e6a1 - <unknown>
>   12:     0x7f9816130f18 - <unknown>
>   13:     0x7f9816133c9c - <unknown>
>   14:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   15:     0x7f9816140c6e - <unknown>
>   16:     0x7f9816130f18 - <unknown>
>   17:     0x7f9816133c9c - <unknown>
>   18:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   19:     0x7f9816140c6e - <unknown>
>   20:     0x7f9816130b0b - <unknown>
>   21:     0x7f9816133c9c - <unknown>
>   22:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   23:     0x7f9816140c6e - <unknown>
>   24:     0x7f9816130b0b - <unknown>
>   25:     0x7f9816133c9c - <unknown>
>   26:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   27:     0x7f9816140c6e - <unknown>
>   28:     0x7f9816130b0b - <unknown>
>   29:     0x7f9816133c9c - <unknown>
>   30:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   31:     0x7f9816130b0b - <unknown>
>   32:     0x7f9816133c9c - <unknown>
>   33:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   34:     0x7f9816140c6e - <unknown>
>   35:     0x7f9816130b0b - <unknown>
>   36:     0x7f9816133c9c - <unknown>
>   37:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   38:     0x7f9816140c6e - <unknown>
>   39:     0x7f9816130f18 - <unknown>
>   40:     0x7f9816133c9c - <unknown>
>   41:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   42:     0x7f9816140c6e - <unknown>
>   43:     0x7f98160670ab - <unknown>
>   44:     0x7f9816130b0b - <unknown>
>   45:     0x7f9816133c9c - <unknown>
>   46:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   47:     0x7f9816140c6e - <unknown>
>   48:     0x7f9816130b0b - <unknown>
>   49:     0x7f9816133c9c - <unknown>
>   50:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   51:     0x7f981602591b - <unknown>
>   52:     0x7f9816130f18 - <unknown>
>   53:     0x7f9816133c9c - <unknown>
>   54:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   55:     0x7f9816140c6e - <unknown>
>   56:     0x7f9816130b0b - <unknown>
>   57:     0x7f9816133c9c - <unknown>
>   58:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   59:     0x7f9816140c6e - <unknown>
>   60:     0x7f9816130b0b - <unknown>
>   61:     0x7f9816133c9c - <unknown>
>   62:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   63:     0x7f9816ab7e10 - <unknown>
>   64:     0x7f9816130f18 - <unknown>
>   65:     0x7f9816133c9c - <unknown>
>   66:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   67:     0x7f9816140c6e - <unknown>
>   68:     0x7f9816130b0b - <unknown>
>   69:     0x7f9816133c9c - <unknown>
>   70:     0x7f9816140bc2 - gtk_widget_snapshot_child
>   71:     0x7f9816140c6e - <unknown>
>   72:     0x7f9816130f18 - <unknown>
>   73:     0x7f9816133c9c - <unknown>
>   74:     0x7f98161402fc - <unknown>
>   75:     0x7f9816147d19 - <unknown>
>   76:     0x7f98162470a7 - <unknown>
>   77:     0x7f981736a70a - <unknown>
>   78:     0x7f981738559e - g_signal_emit_valist
>   79:     0x7f9817386363 - g_signal_emit
>   80:     0x7f98162747b2 - <unknown>
>   81:     0x7f981736a70a - <unknown>
>   82:     0x7f981738615f - g_signal_emit_valist
>   83:     0x7f9817386363 - g_signal_emit
>   84:     0x7f981626373d - <unknown>
>   85:     0x7f981626441e - <unknown>
>   86:     0x7f981726d37f - <unknown>
>   87:     0x7f981726c681 - g_main_context_dispatch
>   88:     0x7f981726cbd8 - <unknown>
>   89:     0x7f981726cc73 - g_main_context_iteration
>   90:     0x7f9816fbbd1d - g_application_run
>   91:     0x56110f9307bb - <unknown>
>   92:     0x56110f7c2cc3 - <unknown>
>   93:     0x56110f956267 - <unknown>
>   94:     0x7f9815a2954a - <unknown>
>   95:     0x7f9815a2960b - __libc_start_main
>   96:     0x56110f76bb85 - <unknown>
>   97:                0x0 - <unknown>
> [evan@k-jinx]~% flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote
> 
> (rnote:2): Gtk-WARNING **: 00:52:44.614: Unknown key gtk-modules in /home/evan/.var/app/com.github.flxzt.rnote/config/gtk-4.0/settings.ini
> 
> (rnote:2): Adwaita-WARNING **: 00:52:44.652: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
>  2023-02-17T05:52:44.668Z DEBUG rnote::app::imp > ... env_logger initialized
>  2023-02-17T05:52:44.757Z DEBUG rnote::canvas   > did not load `engine-config` from settings, was empty
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', rnote-ui/src/strokewidthpicker/strokewidthpreview.rs:97:35
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Desktop (please complete the following information):**
 - OS - Fedora Kinoite 38 Prerelease
 - Version - 0.5.13
 - Installation source - Flatpak
 - Desktop Environment - KDE 5.27

**Additional context**
This issue wasn't happening on Ubuntu 22.10 or Fedora Silverblue 37. Not sure if it's a KDE or Fedora 38 bug, I'm leaning towards the former since I'm running the flatpak build.

**Comment by flxzt** [comment] 2023-02-17 08:11
Duplicate of #504 . Check out the beta (v0.5.14-beta1), it should be fixed there. I  am planning to publish a new bug-fix release soon because of this

**Closed by flxzt** 2023-02-17 08:11 UTC
Labels: bug, duplicate
