### ISSUE TITLE
Delete ony parts of created forms, not the whole form

### ISSUE THREAD

**Issue by reneas** [flxzt/rnote#1163] opened 2024-07-30 08:08 UTC
**Is your feature request related to a problem? Please describe.**  
I really love rnote but one thing that annoys me the most is that you can't remove single lines/segments from created forms. 
When selecting the eraser-option marked in the picture (I don't know the name in english only in german: "Striche aufteilen") and trying to delete only parts of a created form it deletes the whole form.

**Describe the solution you'd like**  
It  should be possible to erase parts of created form as if they were drawn by hand.

**Additional context**  
![image](https://github.com/user-attachments/assets/151f7eac-73a5-4bc7-add0-56fcf2f2ab8a)
![image](https://github.com/user-attachments/assets/730ee080-8a85-4294-af6d-cade8dd59035)

**Comment by RayJW** [comment] 2024-07-30 09:43
I think this is a duplicate of #596 :)

**Comment by Doublonmousse** [comment] 2024-07-30 09:57
Yeah duplicate again.
Duplicate of #596

**Closed by Doublonmousse** 2024-07-30 09:57 UTC

**Comment by reneas** [comment] 2024-07-30 10:08
Sorry, I searched the issues and didn't find that one :(
