### ISSUE TITLE
Make Keyboard shortcuts customziable

### ISSUE THREAD

**Issue by claws99** [flxzt/rnote#973] opened 2024-01-11 08:23 UTC
The app has lot of essential features and tools but using them is quite cumbersome, especially the default keybindings. They are too complex to use.

For instance, while writing with a pen quickly adding a page isn't a single click using UI and keybinding `ctrl+shift+A` requires me to hold 3 keys in weird positions. Also there could be lot of Accessibility issues.

Optimizing keybindings which works for most of the people is tough, therefore expose all actions make keybindings customizable. All apps which scaled has this feature.

I really like how it is done by Sumatrapdfreader: `Settings -> Advanced Settings...` opens a settings text file: [Customize any setting](https://www.sumatrapdfreader.org/settings/settings3-5-1.html) that isn't to your liking:

**Comment by flxzt** [comment] 2024-01-17 09:18
duplicate of #590

**Closed by flxzt** 2024-01-17 09:18 UTC
