### ISSUE TITLE
Add highlight (marker) pen tool

### ISSUE THREAD

**Issue by lokman2k5** [flxzt/rnote#1221] opened 2024-09-17 18:54 UTC
I also have another request to consider which is to add a "recent documents" option in the burger menu.
I'd be happy to help with implementing these!

**Comment by Doublonmousse** [comment] 2024-09-18 05:43
The recent document suggestion is a a duplicate of #993 and the highlighter part is a duplicate of #449.

Though there are additional issues for doing a highlighter (see #891) currently.

I'll close as a duplicate of both.

**Closed by Doublonmousse** 2024-09-18 05:43 UTC
