### ISSUE TITLE
Undo Logic

### ISSUE THREAD

**Issue by maymage** [flxzt/rnote#91] opened 2022-02-05 07:21 UTC
Hi, 

so there's a undo logic problem, which got on my nerves recently

# Reproducer

1. Make `Stroke 1`
2. Make `Stroke 2`
3. Erase `Stroke 1`
4. Hit `Undo` button

* Expected: Undo step 3, that is `Stroke 1` reappears
* Observed: `Stroke 2` vanishes

That means, when ever I accidentally erased to much content, I cannot undo it in a straight forward way.

**Comment by flxzt** [comment] 2022-02-05 10:27
please check for already existing issues, duplicate of #23

**Closed by flxzt** 2022-02-05 10:27 UTC

**Comment by maymage** [comment] 2022-02-05 10:30
Damned, I forgot to check first.. sorry...
