### ISSUE TITLE
single element strokes are not rendered

### ISSUE THREAD

**Issue by SokolovskyMaxim** [flxzt/rnote#681] opened 2023-05-17 15:06 UTC
I often use bulleted lists in my notes, but the bullet points are not always saved. The video clearly demonstrates the error. As far as I noticed, perfectly round stroke shapes are not preserved, which are obtained if you do not shift the pen

https://github.com/flxzt/rnote/assets/106545001/f04c1ab4-4475-4780-b069-55da170b2395

**Comment by flxzt** [comment] 2023-05-18 08:33
They actually are saved/loaded fine, this seems to be an issue when rendering these single-element strokes.

**Comment by PhilDevProg** [comment] 2023-10-06 16:23
This still happens to me on version 0.9

**Comment by flxzt** [comment] 2023-10-13 08:25
Can you confirm that these single-element strokes are actually applied to the canvas? Check `developer mode` in the app menu, and then check the then visible item `developer menu -> visual debugging` in the app menu.
Then for every stroke element that is drawn there should be a small red dot appearing on the canvas.

**Comment by PhilDevProg** [comment] 2023-10-13 10:29
> Can you confirm that these single-element strokes are actually applied to the canvas? Check `developer mode` in the app menu, and then check the then visible item `developer menu -> visual debugging` in the app menu.
> Then for every stroke element that is drawn there should be a small red dot appearing on the canvas.

Yes, they exist and also show up after they are drawn. They are also saved (they do exist in the file after closing and reopening it since I can select them and they show up as a red dot via visual debugging) but they aren't shown when I close and reopen the file.

**Comment by flxzt** [comment] 2023-10-15 14:23
can you provide a `.rnote` file? I can't reproduce it

**Comment by PhilDevProg** [comment] 2023-10-18 09:00
> can you provide a `.rnote` file? I can't reproduce it

Sure:
[test document.zip](https://github.com/flxzt/rnote/files/12999634/test.document.zip)

**Comment by flxzt** [comment] 2023-10-31 09:02
I see, this was a logic error where it does not render when the stroke has multiple elements, but they are all at the exact same position.

**Comment by flxzt** [comment] 2023-11-12 09:17
should be resolved, right?

**Comment by PhilDevProg** [comment] 2023-11-12 09:23
Yes :)

**Closed** 2023-11-12 09:24 UTC
Labels: bug, fixed-upstream
