### ISSUE TITLE
unable to exit tool configuration

### ISSUE THREAD

**Issue by Kuchenmampfer** [flxzt/rnote#742] opened 2023-07-10 11:46 UTC
**Describe the bug**  
When I change certain things in a tools configuration, I can't leave the configuration popup anymore. It seems to block my devices touch input. I can proceed to change the configuration and clicking things on the tool bar does give visual feedback. But switching workspace via gesture, clicking outside of the popup to close it or interacting with the top panes does not work.

**To Reproduce**  
1. Select the drawing tool
2. Click the gear to open the configuration
3. Choose a different option for the pressure curve
4. Click outside of the configuration popup to leave it
5. the popup stays open
6. try to switch workspace via gesture
7. nothing happens
8. Try to interact with the Gnome top panel
9. Nothing happens

**Expected behavior**  
Clicking outside the popup closes it and even with the popup open, Gnome gestures still work.

**Console Output**  
No output apart from `... env_logger initialized`

**Desktop (please complete the following information):**  
 - OS: Fedora Silverblue
 - App Version: Rnote v0.7.1
 - Installation Source: Flatpak
 - Desktop Environment: Gnome 44.2
 - Device: Microsoft Surface Go 2
 - Kernel: Linux fedora 6.3.11-200.fc38.x86_64

**Comment by maymage** [comment] 2023-07-10 11:54
Duplicate of https://github.com/flxzt/rnote/issues/119

**Comment by flxzt** [comment] 2023-07-10 11:54
Thanks for the detailed report. This is a known GTK bug, see issue #206 .

**Closed** 2023-07-10 11:54 UTC
Labels: bug, duplicate
