### ISSUE TITLE
Presentation Mode Options, e.g. a laser pointer

### ISSUE THREAD

**Issue by tipptop3d** [flxzt/rnote#890] opened 2023-11-16 17:08 UTC
For collaboration reasons, we regularly stream our rnote app over discord but the cursor does not get captured, making it very hard to show some concepts to team mates. A feature that would help for this circumstance is something like a powerpoint laser pointer, that disappears after some time automatically, because our current solution of using the normal pen to mark something is really not the best solution.

**Comment by ElbertCode** [comment] 2023-11-23 16:12
Isn't that a duplicate of #476?

**Comment by flxzt** [comment] 2023-11-23 17:51
you're right, I'll close as duplicate

**Closed** 2023-11-23 17:51 UTC
Labels: enhancement
