### ISSUE TITLE
Wacom pen tablet with windows Ink enabled cause pan + zoom to stop working

### ISSUE THREAD

**Issue by jspashett** [flxzt/rnote#1094] opened 2024-05-09 15:51 UTC
**Describe the bug**  
Rnote stops panning or scaling even though ALT / Shift Alt is held down when using a Wacom Pen, With the Wacom Centre installed, due to an interaction with Windows Ink.

**To Reproduce**  
When:
a. using a Wacom pen, with the wacom Centre installed
b. The windows ink support is enabled in Wacom Centre (default)
c. Using the pan or zoom controls with the pen. ALT + Shift Alt

1. Press and hold either ALT or Shift + ALT
2. Put the pen down
3. Move the pen around
4. Observe that an ALT or ALT SHIFT toast message appears blinking rapidly.
5. pick then pen up slighly, still holding pan / zoom.
6. Goto strep 2 until the pen starts drawing on the canvas

*. After a short time the Pan / Zoom will stop, and the pen will draw on the canvas instead, still with the ALT or Shift-alt keys held down

**Expected behavior**  
ALT, or Shift-Alt should do pan/zoom without drawing on the canvas while the respsective key is held down.

**Console Output**  
Run the app in the terminal with `flatpak --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1 run com.github.flxzt.rnote`
and post the output.

Windows instructions would be useful.

**Screenshots**  
![image](https://github.com/flxzt/rnote/assets/49938610/12f4b7e1-db0d-495f-8cce-ac52288efad9)
The wacom centre with Use windows ink setting (on by default)

![image](https://github.com/flxzt/rnote/assets/49938610/dfa4897d-de98-4cdb-aeb6-8c626384ac1c)
After holding ALT for some time for panning, the pen starts to draw instead, still with ALT held down.

**Desktop (please complete the following information):**  
 - OS: Windows 10, build 19045.4291
 - 0.10.1
 - winget install flxzt.rnote
 - Windows 10
 - Direct X 12, Intel Xe graphics family
 - Wacom One, with Wacom Centre installed

**Additional context**  
Workaround: Disable windows ink support in Wacom Centre

**Comment by Doublonmousse** [comment] 2024-05-09 17:00
Duplicate of #1071

**Comment by jspashett** [comment] 2024-05-09 17:34
> Duplicate of #1071

Thanks. Disabling windows Ink does *seems* to fix the problem. Therefore is it related to the Wacom Software on Linkus also. Obviously there is no windows Ink on Linux though.

**Comment by Doublonmousse** [comment] 2024-05-09 17:38
Not really ..
Without windows ink in the wacom settings, pen input is seen as a mouse input from rnote's code whereas it's seen as a pen input otherwise.
That's the reason for the difference.

You'll notice that in doing that, you don't get any support for pressure values.

**Comment by Doublonmousse** [comment] 2024-05-09 17:55
It is the same bug as it applies to all input recognized as pen input by gtk4 (only windows ink on windows right now)

**Closed** 2024-05-18 11:52 UTC
Labels: duplicate
