### ISSUE TITLE
PDF blurry inside rnote

### ISSUE THREAD

**Issue by flwjdfkdi** [flxzt/rnote#1083] opened 2024-04-18 13:41 UTC
When I import a pdf file as vector graphics into rnote the content is shown quite blurry in comparison to if I open it in an usual pdf viewer. As far as I remember this wasn't the case in older versions of rnote.

**To Reproduce**  
1. right click on pdf file
2. open in rnote
3. import

**Expected behavior**  
See a sharp pdf file.

**Screenshots**  
I added two screenshots that show clearly the difference in sharpness (pdf file opened in pdf viewer an rnote).
![Screenshot_20240418_152454](https://github.com/flxzt/rnote/assets/106489649/bd78e413-735d-42b6-9872-2e895c8093cc)
![Screenshot_20240418_152611](https://github.com/flxzt/rnote/assets/106489649/b5f63496-ceb4-4fcb-ac86-9e2c4dfd0292)

**Desktop (please complete the following information):**  
 - OS: [linux: Tuxedo OS 2]
 - App Version: [Rnote v0.10.2]
 - Installation Source: [Flatpak]
 - Desktop Environment: [KDE Plasma version 5.27.10]
 - Display Server: [X11]
 - Input Source: [Mouse and Keyboard]

**Comment by Doublonmousse** [comment] 2024-04-22 10:52
Duplicate of #684 I'd say

**Closed** 2024-04-22 16:05 UTC
Labels: duplicate
