### ISSUE TITLE
Unusable on windows

### ISSUE THREAD

**Issue by AS0007** [flxzt/rnote#692] opened 2023-05-29 17:48 UTC
So i filled an issue with number #689, and who i guess is one of the developers asked me to file a bug report, i am not really a tech guy so i most probably won't be able to provide all what is asked from me here but i will try my best:
The issue is that whenever i try to import a pdf, the app starts having a seizure, like literally. I would go to any of the tools on the upper or lower tool bars and it would just do something as if it's minimizing itself without me clicking the minimize button ofc. This also happens with the tool bar on the left(where you pick type of pen or thickness from). The crashed are either like a seizure where i have enough time to see other apps that run in my background as well(as if it's minimized itself and then comes back as i said) or that it's sort of "blinking" where this would happen so fast and go back to the rnote app so that i don't have time to see the other running background app. This almost happens with everything, even when i click the 3 lines button on the top right.
I am on rnote version 6.0
Windows 10
downloaded from here, the rnote windows installer x86-64

**Comment by dehesselle** [comment] 2023-05-30 20:26
I did a quick test with a random PDF document that I googled ("download test pdf", https://www.orimi.com/pdf-test.pdf) and cannot reproduce your issue. Can you test again with this document?

**Comment by Kneemund** [comment] 2023-05-31 13:52
In addition to testing that, a video showing the behavior you described would be helpful.

**Comment by ulthiel** [comment] 2023-07-24 14:12
Same issue here on Windows 11 with a Surface Pro. If, e.g., I change the pressure curve of the brush, the brush configuration dialog won't disappear anymore no matter what I click on. I have to kill the app via task manager, that's the only way out. These minimizing/disappearing glitches of the window as described above also happen all the time.

**Comment by flxzt** [comment] 2023-07-24 14:18
Can you provide more info or a screenshot/screen recording of those glitches? I can't reproduce this at all, the app is as stable on windows as on linux on my machine.

Regarding the stuck configuration popover: that's already known, you should be able to close it by pressing escape. (see #206)

**Comment by ulthiel** [comment] 2023-07-24 14:59
> > Same issue here [...]
> 
> No, this should be its own issue. I don't see how your problem relates to importing a PDF.

Not the same cause maybe but the same effect certainly.

**Comment by flxzt** [comment] 2023-11-12 09:16
I don't think it is possible to attempt to fix anything based  on the original report. We'd need more clarification here.

**Closed by flxzt** 2023-11-12 09:16 UTC
Labels: bug, cant-reproduce
