### ISSUE TITLE
Custom keyboard shortcuts 

### ISSUE THREAD

**Issue by theIDinside** [flxzt/rnote#1148] opened 2024-07-17 16:39 UTC
It would be superb, if by using keyboard (or some other input) as short cuts.

One instance would be for instance:

Hold down shift + draw => draw straight lines (so that it would toggle straight-line-drawing)

This would also allow for setting an input to be something specifically, instead of just selecting the "shape" toolbox.

While drawing, for instance software logic flow, I might want to alternate drawing boxes or straight lines and hand writing. Now I have to switch to the shapes toolbox and pick the shape (which may or may not be the last one I used).

So, increasing customization would definitely be useful.

**Comment by flxzt** [comment] 2024-07-22 20:22
duplicate of #590

**Closed by flxzt** 2024-07-22 20:22 UTC
