### ISSUE TITLE
Undo does not work properly with erasing, moving things around or duplicating things.

### ISSUE THREAD

**Issue by redtrumpet** [flxzt/rnote#111] opened 2022-02-13 18:58 UTC
When pressing undo after erasing something, I would expect that the erasing is undone. However, the last input stroke is undone, not the erasing.

The same happens after moving something around, either by selecting, or by the vertical space tool or the "Drag strokes base on proximity" tool.

Using undo after duplicating things, something funny happens: First, it undoes the duplicated section, stroke by stroke. Then it undoes the section that was copied. And only then it undoes whatever was done before. [Here is a demonstration](https://imgur.com/rWwMmHy).

**Comment by VodnikAngus** [comment] 2022-02-13 19:00
Duplicate of #23

**Comment by flxzt** [comment] 2022-02-18 12:33
yes, its a known issue, tracking it in #23

**Closed by flxzt** 2022-02-18 12:33 UTC
