### ISSUE TITLE
Opened file was modified on disk

### ISSUE THREAD

**Issue by Tahinli** [flxzt/rnote#1266] opened 2024-10-28 23:36 UTC
**Describe the bug**  
If I spam saving with CTRL + S, I got error says Opened file was modified on disk.

**To Reproduce**  
1. Open a note
2. Write something
3. Spam couple of CTRL + S then wait

**Expected behavior**  
This error shouldn't be seen since only modifier is the app itself.

**Console Output**  
![image](https://github.com/user-attachments/assets/8ae230bc-0f3f-4a60-918d-beaa90f01d3a)

**Screenshots**  
![image](https://github.com/user-attachments/assets/4055b3c9-38ce-48bd-ad7a-3106933507f6)

**Desktop (please complete the following information):**  
 - OS: Fedora 40
 - App Version: Rnote v0.11.0
 - Installation Source: Flatpak
 - Desktop Environment: Hyprland
 - Display Server: Wayland
 - Input Source: Mouse Keyboard and Drawing Tablet

**Additional Detail**
I think this one is different from https://github.com/flxzt/rnote/issues/990. Because mine needs to be triggered by multiple saving process in same app.

**Comment by Kneemund** [comment] 2024-11-02 23:43
Thanks for reporting! I believe that this is a duplicate of #1159 - if not, feel free to re-open.

**Closed by Kneemund** 2024-11-02 23:43 UTC
