### ISSUE TITLE
An obvious black boxes around rnote

### ISSUE THREAD

**Issue by keflag** [flxzt/rnote#1171] opened 2024-08-09 10:47 UTC
**Describe the bug**  
When rnote is running and the software is not maximizing, there is a **clear black box** around the software.

**To Reproduce**  
Open rnote from the desktop.

**Expected behavior**  
When rnote is running and the software is not maximizing, there are no obvious black boxes around the software.

**Console Output**  
I am sorry, but flatpak cannot run on windows.

**Screenshots**  
![image](https://github.com/user-attachments/assets/e8a9b6ac-59d5-4bb6-abfc-5c3cac0dda33)

**Desktop (please complete the following information):**  
 - OS: Windows 10 22H2
 - App Version: Rnote v0.11.0
 - Installation Source: github
 - Desktop Environment: windows default desktop
 - Display Server: --
 - Input Source: Mouse and Keyboard, External Graphics Tablet

**Additional context**  
None.

**Comment by Doublonmousse** [comment] 2024-08-09 15:56
Seems pretty similar to #842. Most likely this is a graphics-related issue with gtk4.
What is the GPU/iGPU you're using and their respective drivers version ? 

At the very least try to see if you can upgrade your GPU drivers and if this fixes the issue or not. 

May be worth to test different rnote versions (as they're using different gtk4 versions, so maybe one would work whilst other wouldn't).

If this doesn't solve the issue, it's probably a gtk4 issue and we'll open an issue upstream : https://gitlab.gnome.org/GNOME/gtk/-/issues/

**Comment by flxzt** [comment] 2024-08-09 18:29
it seems to be a duplicate of #842, let's discuss further in there

**Closed by flxzt** 2024-08-09 18:29 UTC
Labels: bug
