### ISSUE TITLE
Stylus eraser mode "sticks" for one more stroke

### ISSUE THREAD

**Issue by pavel-the-best** [flxzt/rnote#170] opened 2022-05-12 18:43 UTC
**Describe the bug**
Instead of immediately switching to pen eraser stays for one more stroke after I let go of the eraser button on the stylus.

**To Reproduce**
1. Press and hold the eraser button on the stylus
2. Let go of it
3. Try to draw something with a "pen"
4. See that the tool for the current stroke is still eraser

**Expected behavior**
I expect to be able to draw immediately after letting go of the eraser button.

** Console Output **
None

**Desktop (please complete the following information):**
 - OS: Gentoo GNU/Linux
 - Installation source: build from source commit 2b8248e60f010c3bf5df91f0ed849cbb47fcf367
 - Desktop Environment: KDE Plasma 5.23

**Additional context**
Wacom in-screen sensor & Wacom Bamboo Ink stylus, the issue is reproducible with other styluses

**Comment by pavel-the-best** [comment] 2022-05-12 18:45
Actually I have noticed that after I let go of eraser button, the animation of switching to brush is displayed, but immediately after it ends the mode switches back to eraser.

**Comment by flxzt** [comment] 2022-05-12 19:53
You are supposed to only click, no need to hold the button when starting the eraser. That way you could also modify some eraser settings when you click it while hovering before you actually start erasing

**Comment by Danacus** [comment] 2022-05-13 06:01
I guess that does work, but it feels a bit odd and is not how other programs work. Perhaps it would be nice to have a configurable option.

**Comment by N3xed** [comment] 2022-05-13 10:32
> You are supposed to only click, no need to hold the button when starting the eraser. That way you could also modify some eraser settings when you click it while hovering before you actually start erasing

This won't work with some styluses though. For example, I use a Surface Pen where I use the other end to erase, in v0.4 this worked flawlessly but now after I turn around the pen (to write again) I have to stroke once before it switches back to the pen tool.

**Comment by SzoDavid** [comment] 2022-05-14 14:48
I really like the current implementation, so I think just a checkbox in the settings to make it togglable would be the best.

**Comment by flxzt** [comment] 2022-05-14 15:08
Not sure what version you are referring to, but the latest version (v0.5.3) has the behaviour I want to keep.  
@pavel-the-best this should be fixed for you, right?

**Comment by SzoDavid** [comment] 2022-05-14 15:15
Sorry for that. I was referring to v0.5.1 where by pressing the earser button on the stylus, the program would switch to earser mode, and then by lifting up the stylus it would switch back to pen mode.

**Comment by flxzt** [comment] 2022-05-14 15:19
yeah, the difference would be whether you'd need to hold the button. In v0.5.3 you have to hold it. But since this affects a couple of internals and is not easily made as a configurable option, I will stick to the `you will need to hold it´ behaviour. This maps more cleanly to how input events are received by gtk and is how drawing tablets expect this to be handled

**Comment by SzoDavid** [comment] 2022-05-14 15:41
In that case, I'm perfectly fine with this as well. Thank you.

**Comment by pavel-the-best** [comment] 2022-05-14 16:51
@flxzt, yes, it works for me, thank you.

However, I have caught a strange bug: the buttons occasionally "slide" (primary becomes eraser, eraser stops working; after some time primary stops working even as an eraser), but I can't consistently reproduce it.

**Comment by flxzt** [comment] 2022-05-14 17:22
thats really odd. Please keep an eye out if there are certain conditions that can reproduce it, and file a new bug. Could be with the this new system how pen modes work now.

**Comment by flxzt** [comment] 2022-05-14 17:23
but since this one is fixed, I'll close it.

**Closed by flxzt** 2022-05-14 17:23 UTC
Labels: bug
